---
title: "sandbox"
author: "Crista Gregg"
date: "7/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
```

## get data
```{r connection}
library(tidyverse)
combined <- read_csv('combined.csv')[,-1] %>%
  mutate(Season = factor(ifelse(Month %in% c(3,4,5), "Spring", ifelse(Month %in% c(6,7,8), 'Summer', ifelse(Month %in% c(9,10,11), 'Fall', 'Winter')))))

str(combined)

combined$Month <- factor(combined$Month)
levels(combined$Month) <- month.abb

ggplot(combined, aes(Season, total_acres_burned)) +
  geom_boxplot()


ggplot(combined, aes(total_fires)) +
  geom_histogram(aes(fill = Season)) 

ggplot(combined, aes(Season, total_fires)) +
  geom_boxplot() +
  theme_minimal()

plot_ly(combined, color = ~Season, y = ~total_fires, alpha = 0.3, type = 'box')
?plot_ly
combined %>% 
  group_by(Season) %>%
  summarise(mean_number_fires = mean(total_fires), median_number_fires = median(total_fires), mean_fire_size = mean(total_acres_burned)/mean(total_fires), median_fire_size = median(total_acres_burned)/median(total_fires))
```
#create plots
```{r}
#summarize across summer months
combined2 <- combined %>% filter(State == 'CA') %>%
  group_by(Year) %>%
  summarise(`Yearly Average Temperature` = mean(avg_temp), 
            `Yearly Average High Temperature` = mean(max_temp),
            `Yearly Average Drought Severity` = mean(drought_severity),
            `Total Acres Burned` = sum(total_acres_burned),
            `Total Fires` = sum(total_fires)) %>%
  pivot_longer(cols = `Yearly Average Temperature`:`Total Fires`) %>%
  #group_by(name) %>%
  #mutate(scaled = scale(value)) %>%
  filter(name == 'Yearly Average Temperature' | name == 'Total Fires') %>%
  pivot_wider(values_from = value) 



```

#model fitting
```{r}
library(caret)
library(gbm)
state <- 'CA'
modeling <- filter(combined, State == state)
modeling

train_split <- 0.8
train_rows <- sample(nrow(modeling), train_split*nrow(modeling))
train <- modeling[train_rows,]
test <- modeling[-train_rows,]


lm.fit <- train(total_fires ~ avg_temp + drought_severity + avg_precip + Month + avg_precip:Month + drought_severity:Month + avg_temp:Month, data = train,
                method = 'lm',
                preProcess = c('center', 'scale'),
                trControl = trainControl('cv', number = 10))
  
lm.fit$results[2:4]

lm.pred <- predict(lm.fit, modeling[-train_rows,])

postResample(lm.pred, modeling$total_fires[-train_rows])

```
```{r}
tree.fit <- train(total_fires ~ avg_temp + drought_severity + avg_precip + Month, data = train,
                 method = 'rpart',
                 trControl = trainControl('cv', number = 10))

tree.fit
knn.fit$results[best, 1:4]   
library(rpart.plot)
rpart.plot(tree.fit$finalModel)#;text(tree.fit$finalModel, pretty = T)
```
```{r}
data <- modeling[train_rows,] %>%
  filter(State == state) %>%
  select(total_fires, avg_temp, drought_severity, avg_precip, Month, Year)

rf.fit <- train(total_fires ~ .,
                data = data,
                 method = 'rf',
                 preProcess = c('center', 'scale'),
                 trControl = trainControl('cv', number = 5),
                tuneGrid = data.frame(mtry = seq(10, 20, by = 2))
                )
rf.fit
seq(10,20, by =2)
varImp(rf.fit)
plot.temp<-3

plot.year<-plot(boost.fit$finalModel,i="Year",main='Increasing Year')
plot.precip<-plot(boost.fit$finalModel,i="avg_precip", main='Increasing Avg Precip')
plot.drought<-plot(boost.fit$finalModel,i="drought_severity",main='Increasing Drought Severity', lwd = 2)
gridExtra::grid.arrange(plot.temp, plot.year, plot.precip, plot.drought, ncol = 2)
?plot.gbm
getModelInfo('rf')
```
```{r}
preProcess

library(randomForest)
importance(rf.fit$finalModel)
varImpPlot(rf.fit$finalModel, n.var = 5, main = 'Variable Importance')

important <- data.frame(variable = rownames(rf.fit$finalModel$importance), importance = rf.fit$finalModel$importance)
ggplot(head(important), aes(reorder(variable, IncNodePurity), IncNodePurity)) +
         geom_bar(stat = 'identity', fill = 'darkblue')  +
         coord_flip() +
  labs(x = 'Variable', y = 'Variable Importance')

boost.fit$bestTune$n.trees
best <- which.min(boost.fit$results$RMSE)
boost.fit$results[best,1:7]
```
```{r get prediction}
avg_temp <- 75
drought_severity <- 0
avg_precip <- 4
Year <- 2000
Month <- 'Jul'

predict(rf.fit, data.frame(avg_temp = avg_temp, drought_severity = drought_severity, avg_precip = avg_precip, Year = Year, Month = Month))
```


